[package]
name = "notes-r-ust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
inquire = { version = "0.7.5", features = ["editor"] }
rusqlite = { version = "0.36", features = ["bundled"] }
ansi_term = "0.12"
